### PR TITLE
interrupt solution using soft device libs

### LINKED ISSUE #9: Busy wait vs. wait for interrupt
The `lf_nanosleep` function in `lf_nrf52_support.c` busy waits. It would be far more energy efficient to wait for interrupt. If the event queue is empty, that is all it needs to do. Otherwise, if the requested wait interval is large enough, it should set up a timer interrupt for the time of the first event on the event queue. To perform a wait for interrupt on the Arm Cortex M4, just use the following line of code:
```
__WFI()
```

### LINKED ISSUE #10: Physical actions not supported
A call to `lf_schedule()` in an ISR results in an error like the following:
```
FATAL ERROR: _lf_advance_logical_time(): Attempted to move time to 7000000000, which is past the head of the event queue, 6480087000.
```
The reason is that in `lf_nrf52_support.c`, there is a variable `INT_RAISED` that needs to get set when an interrupt occurs. For now, maybe we can set this in the user code, but then it needs to be reset and mutex will be needed.

### PR DESCRIPTION
**Pull request by gundralaa**
Addressed issue 9 and implemented interrupts without mutex system.

### CODE REVIEW

File: platform/lf_nrf52_support.c [hunk 1]
```diff
@@ -39,19 +39,30 @@ THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
...
 /**
  * Keep track of interrupts being raised.
  * Allow sleep to exit with nonzero return on interrupt.
  */
-uint8_t INT_RAISED = 0;
+bool _lf_interrupted = false;
+uint8_t _lf_nested_region = 0;
+
+// timer event handler
+void lf_timer_event_handler(nrf_timer_event_t event_type, void *p_context);
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c]: It seems this declaration is not needed because the definition is below and there is no reference to this function in between.

File: platform/lf_nrf52_support.c [hunk 2]
```diff
@@ -104,6 +111,18 @@ void calculate_epoch_offset() {
  */
 uint32_t _lf_previous_timer_time = 0u;
 
+void lf_timer_event_handler(nrf_timer_event_t event_type, void *p_context)
+{
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c]: For consistency, I suggest putting "{" on the previous line.

File: platform/lf_nrf52_support.c [hunk 3]
```diff
@@ -104,6 +111,18 @@ void calculate_epoch_offset() {
  */
 uint32_t _lf_previous_timer_time = 0u;
 
+void lf_timer_event_handler(nrf_timer_event_t event_type, void *p_context)
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c]: Function comment needed. What does this do?

File: platform/lf_nrf52_support.c [hunk 4]
```diff
@@ -104,6 +111,18 @@ void calculate_epoch_offset() {
...
+{
+    // interrupted by timer first
+    if (event_type == NRF_TIMER_EVENT_COMPARE2)
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c]: Add comment. What is the meaning of NRF_TIMER_EVENT_COMPARE2? Also, add curly braces.

File: platform/lf_nrf52_support.c [hunk 5]
```diff
@@ -104,6 +111,18 @@ void calculate_epoch_offset() {
...
+        _lf_interrupted = false;
+    // overflow handle
+    if (event_type == NRF_TIMER_EVENT_COMPARE3) {
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c:134]: Comment needed: What is the meaning of NRF_TIMER_EVENT_COMPARE3?

File: platform/lf_nrf52_support.c [hunk 6]
```diff
@@ -104,6 +111,18 @@ void calculate_epoch_offset() {
...
+        nrfx_timer_clear(&g_lf_timer_inst);
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c]: Is clearing really the right thing to do? I'm guessing that NRF_TIMER_EVENT_COMPARE3 means that the timer hit its maximum and stopped? If it actually overflowed, then clearing it will introduce a timing offset, which seems like an error to me.

File: platform/lf_nrf52_support.c [hunk 7]
```diff
@@ -116,11 +135,26 @@ void lf_initialize_clock() {
...
+    nrfx_timer_config_t timer_conf = {
+        .frequency = NRF_TIMER_FREQ_1MHz,
+        .mode = NRF_TIMER_MODE_TIMER,
+        .bit_width = NRF_TIMER_BIT_WIDTH_32,
+        .interrupt_priority = 7, // lowest
+        .p_context = NULL,
+    };
+
+    nrfx_timer_init(&g_lf_timer_inst, &timer_conf, &lf_timer_event_handler);
+    // overflow channel
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c]:
```suggestion
    // Enable an interrupt to occur with event type NRF_TIMER_CC_CHANNEL3
    // when the timer reaches its maximum value and is about to overflow.
```

File: platform/lf_nrf52_support.c [hunk 8]
```diff
@@ -143,19 +177,11 @@ int lf_clock_gettime(instant_t* t) {
...
-    }
-
-    *t = ((instant_t)current_timer_time) * 1000 + _lf_time_epoch_offset;
-
-    _lf_previous_timer_time = current_timer_time;
+    uint32_t curr_time;
+    // capture latest timer value
+    curr_time = nrfx_timer_capture(&g_lf_timer_inst, NRF_TIMER_CC_CHANNEL1);
+    *t = ((instant_t)curr_time) * 1000 + _lf_time_epoch_offset;
+    _lf_previous_timer_time = curr_time;
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c]: I think this code still needs to correct the returned value in *t if current_timer_time < _lf_previous_timer_time because there is a race condition. Suppose the timer hits `~0x0` and triggers an interrupt but before the interrupt is handled, some piece of code calls `lf_clock_gettime`.  Then the `_lf_time_epoch_offset` will not have been updated and the time value returned will be off by `(1LL << 32)` microseconds. This could cause the LF program to freeze.  This would probably be a very rare event, so it's not likely to show up in testing. Careful commenting of the code is important.

If I am wrong about this, then `_lf_previous_timer_time` is no longer used in this code and should be removed.

File: platform/lf_nrf52_support.c [hunk 9]
```diff
@@ -165,10 +191,6 @@ int lf_clock_gettime(instant_t* t) {
  * @return 0 on success, platform-specific error number otherwise.
  */
 int lf_mutex_lock(lf_mutex_t* mutex) {
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c]: Shouldn't these mutex functions just be removed? The unthreaded runtime does not call them.

File: platform/lf_nrf52_support.c [hunk 10]
```diff
@@ -216,40 +221,28 @@ int lf_mutex_init(lf_mutex_t* mutex) {
...
-        lf_mutex_lock((lf_mutex_t*)head);
-        head = head->next;
-    }
-    int result = (INT_RAISED == 0)? 0 : -1;
-    INT_RAISED = 0;
+    // enable nvic
+    sd_nvic_critical_region_exit(_lf_nested_region);
+    
+    // reset by timer interrupt callback
+    _lf_interrupted = true;
```
Comment (edwardalee) [inline platform/lf_nrf52_support.c]: Possible race condition here. I think `_lf_interrupted` needs to be set before exiting the critical section. Otherwise, an interrupt could occur between line 232 and line 235 and `_lf_interrupted` will have the wrong value.

Also, `_lf_interrupted` is misnamed because it has value `true` when an interrupt has *not* occurred.

**Review by edwardalee — CHANGES_REQUESTED** [review]
Very nice!!  This will actually solve our core problem for now, making the use of mutexes in the unthreaded runtime much less urgent. It still has the potential disadvantage that interrupts are only enabled during `lf_nanosleep`, but for interrupts that call `lf_schedule` and do nothing else, this does not actually reduce the precision of responses.  Does it increase the risk of interrupts being missed altogether?

There are a couple of potentially problematic race conditions that I've identified in the detailed comments. I think they are easily fixed.

For some reason, src/AccelerometerDisplay.lf no longer compiles in this branch:
```
lfc src/AccelerometerDisplay.lf
...
file:/Users/eal/git/lf-buckler/src/lib/Display.lf:17:10: fatal error: display.h: No such file or directory
```

File: platform/lf_nrf52_support.c (hunk 10 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c]: moved and added some comments. Its a little confusing but _lf_interrupted is default set true meaning that an interrupt other than the requested time interrupt from the timer fired and exited the sd_app_evt_wait(). The timer callback sets _lf_interrupted false meaning no need to re check the event queue.

File: platform/lf_nrf52_support.c (hunk 9 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c]: removed

File: platform/lf_nrf52_support.c (hunk 8 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c]: I've added the check back and a flag to make sure the interrupt does add to the epoch_offset twice. I might be missing something however, I'll think about this issue more.

File: platform/lf_nrf52_support.c (hunk 6 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c]: makes sense, removed the clear

File: platform/lf_nrf52_support.c (hunk 5 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c:134]: added

File: platform/lf_nrf52_support.c (hunk 4 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c]: added

File: platform/lf_nrf52_support.c (hunk 3 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c]: added

File: platform/lf_nrf52_support.c (hunk 1 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c]: removed

File: platform/lf_nrf52_support.c (hunk 2 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c]: added

File: platform/lf_nrf52_support.c (hunk 7 above)
Comment (gundralaa) [reply platform/lf_nrf52_support.c]: changed

File: platform/lf_nrf52_support.c (hunk 10 above)
Comment (edwardalee) [reply platform/lf_nrf52_support.c]: Still, I suggest either changing the polarity (false by default, true if interrupted) or changing the name of the variable to `_lf_uninterrupted`.

**Review by edwardalee — APPROVED** [review]
LGTM!  Added a minor suggestion. Let's merge.

File: platform/lf_nrf52_support.c (hunk 10 above)
Comment (lhstrh) [reply platform/lf_nrf52_support.c]: I think setting to `false` by default makes more sense.
